# Generated by Django 5.1.6 on 2025-02-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
